# Generated by Django 5.1.1 on 2026-02-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_number', models.CharField(max_length=20)),
                ('appointment_data', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('doctor', models.CharField(max_length=20)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_speciality', models.CharField(max_length=20)),
                ('doctor_fee', models.IntegerField()),
                ('doctor_slots', models.IntegerField()),
                ('doctor_otp', models.CharField(max_length=10)),
                ('doctor_number', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(max_length=20)),
                ('doctor_password', models.CharField(max_length=20)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='doctors/')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.CharField(max_length=5)),
                ('patient_otp', models.CharField(max_length=10)),
                ('patient_number', models.CharField(max_length=20)),
                ('patient_email', models.EmailField(max_length=20)),
                ('patient_password', models.CharField(max_length=20)),
                ('patient_blood_group', models.CharField(max_length=20)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_weight', models.IntegerField()),
                ('patient_height', models.IntegerField()),
                ('patient_image', models.ImageField(upload_to='patients/')),
            ],
        ),
        migrations.CreateModel(
            name='pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacist_name', models.CharField(max_length=20)),
                ('pharmacist_number', models.CharField(max_length=20)),
                ('pharmacist_email', models.EmailField(max_length=20)),
                ('pharmacist_otp', models.CharField(max_length=10)),
                ('pharmacist_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('medicines', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist_name', models.CharField(max_length=20)),
                ('receptionist_number', models.CharField(max_length=20)),
                ('receptionist_email', models.EmailField(max_length=20)),
                ('receptionist_otp', models.CharField(max_length=10)),
                ('receptionist_password', models.CharField(max_length=10)),
            ],
        ),
    ]
