# Generated by Django 6.0.2 on 2026-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='patients/'),
        ),
    ]
