# Generated by Django 6.0.2 on 2026-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='pharmacist_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='receptionist_otp',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
